services:
  api:
    build: .
    links:
      - database
    ports:
      - 8080:8080
  database:
    image: mongo:3.5.5
    container_name: "upper-api-database"
    ports:
      - 27017:27017
  ui:
    build: ./simple-ui